{
    "i": {
        "h": {
            "title": "video player",
            "videoId": "[object Object]",
            "width": "640",
            "height": "390",
            "sandbox": "allow-presentation",
            "events": {},
            "host": "https://www.youtube.com"
        }
    },
    "h": {},
    "o": null,
    "j": 31,
    "u": true,
    "m": [],
    "l": {
        "j": false,
        "u": 7,
        "l": [],
        "m": 0,
        "h": [
            null,
            "onReady",
            null,
            null,
            "onStateChange",
            null,
            null
        ],
        "i": {
            "onReady": [
                1
            ],
            "onStateChange": [
                4
            ]
        },
        "C": false
    },
    "H": {
        "onReady": true,
        "onStateChange": true
    },
    "closure_uid_603087010": 5,
    "id": 5,
    "C": "player",
    "P": {},
    "playerInfo": {
        "apiInterface": [
            "cueVideoById",
            "loadVideoById",
            "cueVideoByUrl",
            "loadVideoByUrl",
            "playVideo",
            "pauseVideo",
            "stopVideo",
            "clearVideo",
            "getVideoBytesLoaded",
            "getVideoBytesTotal",
            "getVideoLoadedFraction",
            "getVideoStartBytes",
            "cuePlaylist",
            "loadPlaylist",
            "nextVideo",
            "previousVideo",
            "playVideoAt",
            "setShuffle",
            "setLoop",
            "getPlaylist",
            "getPlaylistIndex",
            "getPlaylistId",
            "loadModule",
            "unloadModule",
            "setOption",
            "getOption",
            "getOptions",
            "mute",
            "unMute",
            "isMuted",
            "setVolume",
            "getVolume",
            "seekTo",
            "getPlayerMode",
            "getPlayerState",
            "getPlaybackRate",
            "setPlaybackRate",
            "getAvailablePlaybackRates",
            "getPlaybackQuality",
            "setPlaybackQuality",
            "getAvailableQualityLevels",
            "getCurrentTime",
            "getDuration",
            "addEventListener",
            "removeEventListener",
            "getDebugText",
            "getVideoData",
            "addCueRange",
            "removeCueRange",
            "setSize",
            "getApiInterface",
            "destroy",
            "showVideoInfo",
            "hideVideoInfo",
            "isVideoInfoVisible",
            "getSphericalProperties",
            "setSphericalProperties",
            "getVideoEmbedCode",
            "getVideoUrl",
            "getMediaReferenceTime",
            "getSize",
            "logImaAdEvent"
        ],
        "videoBytesLoaded": 0.03236248465872865,
        "videoBytesTotal": 1,
        "videoLoadedFraction": 0.03236248465872865,
        "videoStartBytes": 0,
        "playlist": null,
        "playlistIndex": -1,
        "playlistId": null,
        "option": null,
        "options": [],
        "muted": false,
        "volume": 100,
        "playerMode": {},
        "playerState": 2,
        "playbackRate": 1,
        "availablePlaybackRates": [
            0.25,
            0.5,
            0.75,
            1,
            1.25,
            1.5,
            1.75,
            2
        ],
        "playbackQuality": "hd1080",
        "availableQualityLevels": [
            "hd2160",
            "hd1440",
            "hd1080",
            "hd720",
            "large",
            "medium",
            "small",
            "tiny",
            "auto"
        ],
        "currentTime": 5.794359,
        "duration": 773.241,
        "debugText": "{\n  \"debug_videoId\": \"2d4L1flXhLY\",\n  \"debug_playbackQuality\": \"unknown\",\n  \"debug_date\": \"Fri Dec 16 2022 06:14:02 GMT-0500 (Eastern Standard Time)\"\n}",
        "videoInfoVisible": false,
        "sphericalProperties": {},
        "videoEmbedCode": "<iframe width=\"640\" height=\"390\" src=\"https://www.youtube.com/embed/2d4L1flXhLY\" title=\"\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>",
        "videoUrl": "https://www.youtube.com/watch?t=5&v=2d4L1flXhLY",
        "mediaReferenceTime": 5.794359,
        "size": {
            "width": 640,
            "height": 390
        },
        "videoData": {
            "video_id": "2d4L1flXhLY",
            "author": "Patty Mayo",
            "title": "PART 2: TRAP HOUSE HAS AN ENTIRE HIDDEN APARTMENT",
            "isPlayable": true,
            "errorCode": null,
            "video_quality": "hd1080",
            "video_quality_features": [
                "hfr"
            ],
            "backgroundable": true,
            "eventId": "-1KcY9DcDtPAiwTrtqbQCg",
            "cpn": "JSRG51QjVtHDGv2n",
            "isLive": false,
            "isWindowedLive": false,
            "isManifestless": false,
            "allowLiveDvr": false,
            "isListed": true,
            "isMultiChannelAudio": false,
            "hasProgressBarBoundaries": false,
            "isPremiere": false,
            "itct": "CAAQu2kiEwiQxsiJgf77AhVT4IIKHWubCao=",
            "progressBarStartPositionUtcTimeMillis": null,
            "progressBarEndPositionUtcTimeMillis": null,
            "paidContentOverlayDurationMs": 0
        },
        "currentTimeLastUpdated_": 1671189244.842
    },
    "videoTitle": "PART 2: TRAP HOUSE HAS AN ENTIRE HIDDEN APARTMENT"
}